/**
 * Seed via Vercel API — envoie les apps à POST /api/apps
 * Usage: node scripts/seed-via-api.mjs
 */

const BASE_URL = 'https://trusti-git-main-notsogeeks-projects.vercel.app';

const APPS = [
  // MESSAGERIE
  { name:'WhatsApp', grade:'C', category:'Messagerie', icon:'💬', color:'bg-green-600', developer:'Meta', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:2, reason:'Chiffrement de bout en bout mais les métadonnées (avec qui tu parles, quand) sont partagées avec Meta.', description:'Messagerie instantanée avec 2 milliards d\'utilisateurs. Chiffrement E2E activé par défaut.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.whatsapp', appleStoreUrl:'https://apps.apple.com/fr/app/whatsapp-messenger/id310633997', website:'https://www.whatsapp.com' },
  { name:'Signal', grade:'A', category:'Messagerie', icon:'🔒', color:'bg-blue-600', developer:'Signal Foundation', jurisdiction:'USA', isEuropean:false, isOpenSource:true, popularity:8, reason:'Chiffrement de bout en bout le plus avancé, open source, à but non lucratif. Collecte minimale de données.', description:'La référence en matière de messagerie privée. Open source, sans publicité, sans tracking.', playStoreUrl:'https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms', appleStoreUrl:'https://apps.apple.com/fr/app/signal-private-messenger/id874139669', website:'https://signal.org', githubUrl:'https://github.com/signalapp' },
  { name:'Telegram', grade:'B', category:'Messagerie', icon:'✈️', color:'bg-sky-500', developer:'Telegram FZ-LLC', jurisdiction:'Émirats Arabes Unis', isEuropean:false, isOpenSource:false, popularity:9, reason:'Chiffrement E2E disponible uniquement en mode "secret". Les chats normaux sont stockés sur leurs serveurs.', description:'Messagerie rapide avec groupes, canaux et bots. E2E seulement en mode secret.', playStoreUrl:'https://play.google.com/store/apps/details?id=org.telegram.messenger', appleStoreUrl:'https://apps.apple.com/fr/app/telegram-messenger/id686449807', website:'https://telegram.org' },
  { name:'Messenger', grade:'E', category:'Messagerie', icon:'💙', color:'bg-blue-500', developer:'Meta', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:15, reason:'Appartient à Meta. Collecte massive de données personnelles, graphe social, historique de messages utilisé pour le ciblage publicitaire.', description:'Messagerie de Facebook. Intégration profonde avec l\'écosystème Meta.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.facebook.orca', appleStoreUrl:'https://apps.apple.com/fr/app/messenger/id454638411', website:'https://www.messenger.com' },
  { name:'Discord', grade:'D', category:'Messagerie', icon:'🎮', color:'bg-indigo-600', developer:'Discord Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:22, reason:'Collecte le contenu des messages, activité, adresse IP. Pas de chiffrement de bout en bout. Historique accessible par Discord.', description:'Plateforme de communication vocale, vidéo et textuelle, populaire chez les gamers et communautés.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.discord', appleStoreUrl:'https://apps.apple.com/fr/app/discord/id985746746', website:'https://discord.com' },
  { name:'Viber', grade:'C', category:'Messagerie', icon:'📳', color:'bg-purple-600', developer:'Rakuten Viber', jurisdiction:'Luxembourg', isEuropean:true, isOpenSource:false, popularity:35, reason:'Chiffrement E2E par défaut. Siège européen mais collecte des données de contacts et comportements.', description:'Messagerie et appels gratuits. Populaire en Europe centrale et en France.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.viber.voip', appleStoreUrl:'https://apps.apple.com/fr/app/viber-messenger/id382617920', website:'https://www.viber.com' },

  // RÉSEAUX SOCIAUX
  { name:'Instagram', grade:'E', category:'Réseaux sociaux', icon:'📸', color:'bg-pink-600', developer:'Meta', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:3, reason:'Collecte massive : localisation, contacts, données biométriques via reconnaissance faciale, historique de navigation. Profiling publicitaire intensif.', description:'Réseau social de partage de photos et vidéos. 2 milliards d\'utilisateurs actifs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.instagram.android', appleStoreUrl:'https://apps.apple.com/fr/app/instagram/id389801252', website:'https://www.instagram.com' },
  { name:'TikTok', grade:'E', category:'Réseaux sociaux', icon:'🎵', color:'bg-slate-950', developer:'ByteDance', jurisdiction:'Chine', isEuropean:false, isOpenSource:false, popularity:4, reason:'Appartient à ByteDance (Chine). Collecte biométrique, contenu du presse-papiers, localisation précise. Préoccupations gouvernementales en France et en Europe.', description:'Réseau social de courtes vidéos. 1,5 milliard d\'utilisateurs actifs mensuels.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically', appleStoreUrl:'https://apps.apple.com/fr/app/tiktok/id835599320', website:'https://www.tiktok.com' },
  { name:'Facebook', grade:'E', category:'Réseaux sociaux', icon:'👥', color:'bg-blue-700', developer:'Meta', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:5, reason:'Le pire en termes de vie privée. Graphe social, tracking cross-sites, données partagées avec annonceurs, scandales répétés (Cambridge Analytica).', description:'Premier réseau social mondial. 3 milliards d\'utilisateurs actifs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.facebook.katana', appleStoreUrl:'https://apps.apple.com/fr/app/facebook/id284882215', website:'https://www.facebook.com' },
  { name:'Snapchat', grade:'D', category:'Réseaux sociaux', icon:'👻', color:'bg-yellow-400', developer:'Snap Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:11, reason:'Collecte la localisation en continu, les contacts, et utilise des filtres AR pouvant analyser le visage. Messages éphémères mais données persistantes.', description:'Application de messagerie éphémère avec filtres et Stories. Populaire chez les 15-30 ans.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.snapchat.android', appleStoreUrl:'https://apps.apple.com/fr/app/snapchat/id447188370', website:'https://www.snapchat.com' },
  { name:'X (Twitter)', grade:'D', category:'Réseaux sociaux', icon:'🐦', color:'bg-slate-900', developer:'X Corp.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:14, reason:'Collecte des données de navigation, localisation, et les partage avec des tiers. Politique de confidentialité dégradée depuis le rachat par Elon Musk.', description:'Réseau social de microblogging. 350 millions d\'utilisateurs actifs quotidiens.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.twitter.android', appleStoreUrl:'https://apps.apple.com/fr/app/x/id333903271', website:'https://x.com' },
  { name:'LinkedIn', grade:'D', category:'Réseaux sociaux', icon:'💼', color:'bg-blue-700', developer:'Microsoft', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:16, reason:'Collecte des données professionnelles et comportementales extensives. Profiling pour le recrutement et la publicité. Partage avec Microsoft.', description:'Réseau social professionnel. 1 milliard de membres dans le monde.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.linkedin.android', appleStoreUrl:'https://apps.apple.com/fr/app/linkedin/id288429040', website:'https://www.linkedin.com' },
  { name:'Threads', grade:'E', category:'Réseaux sociaux', icon:'🧵', color:'bg-slate-900', developer:'Meta', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:18, reason:'Appartient à Meta. Collecte un nombre exceptionnel de données : santé, finances, localisation précise, historique de navigation, tous liés à ton identité.', description:'Réseau social textuel de Meta, concurrent de X/Twitter. Intégré à Instagram.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.instagram.barcelona', appleStoreUrl:'https://apps.apple.com/fr/app/threads/id6446901002', website:'https://www.threads.net' },
  { name:'Pinterest', grade:'D', category:'Réseaux sociaux', icon:'📌', color:'bg-red-600', developer:'Pinterest Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:28, reason:'Collecte les centres d\'intérêt, comportements de navigation et achats potentiels pour le ciblage publicitaire. Partage de données avec des tiers.', description:'Réseau social de partage d\'images et d\'inspiration. 500 millions d\'utilisateurs actifs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.pinterest', appleStoreUrl:'https://apps.apple.com/fr/app/pinterest/id429047995', website:'https://www.pinterest.fr' },
  { name:'BeReal', grade:'C', category:'Réseaux sociaux', icon:'📷', color:'bg-slate-800', developer:'BeReal SAS', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:38, reason:'Startup française. Collecte localisation et contacts mais dans un contexte plus limité que les grands réseaux. Politique transparente.', description:'Réseau social anti-filtre : une photo authentique par jour, façade et selfie simultanés.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.bereal.ft', appleStoreUrl:'https://apps.apple.com/fr/app/bereal-votre-ami-authentique/id1459645446', website:'https://bere.al' },
  { name:'Mastodon', grade:'A', category:'Réseaux sociaux', icon:'🦣', color:'bg-purple-700', developer:'Mastodon gGmbH', jurisdiction:'Allemagne', isEuropean:true, isOpenSource:true, popularity:55, reason:'Décentralisé, open source, sans publicité ni tracking. Tu choisis ton instance et ses règles de confidentialité. Fondation allemande à but non lucratif.', description:'Réseau social décentralisé et fédéré. Alternative éthique à Twitter/X.', playStoreUrl:'https://play.google.com/store/apps/details?id=org.joinmastodon.android', appleStoreUrl:'https://apps.apple.com/fr/app/mastodon-for-iphone/id1571998974', website:'https://joinmastodon.org', githubUrl:'https://github.com/mastodon/mastodon' },
  { name:'Bluesky', grade:'B', category:'Réseaux sociaux', icon:'🦋', color:'bg-sky-500', developer:'Bluesky PBLLC', jurisdiction:'USA', isEuropean:false, isOpenSource:true, popularity:52, reason:'Protocole AT ouvert et fédéré. Moins de tracking que les grands réseaux. Code open source. Alternative sérieuse à X/Twitter.', description:'Réseau social décentralisé basé sur le protocole AT. Alternative à X/Twitter en pleine croissance.', playStoreUrl:'https://play.google.com/store/apps/details?id=xyz.blueskyweb.app', appleStoreUrl:'https://apps.apple.com/fr/app/bluesky-social/id6444370199', website:'https://bsky.app' },

  // MULTIMÉDIA
  { name:'YouTube', grade:'D', category:'Multimédia', icon:'▶️', color:'bg-red-600', developer:'Google', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:7, reason:'Appartient à Google. Profiling exhaustif basé sur les vidéos regardées. Publicités ciblées, historique de visionnage utilisé pour la personnalisation.', description:'La plus grande plateforme vidéo mondiale. 2,5 milliards d\'utilisateurs actifs mensuels.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.google.android.youtube', appleStoreUrl:'https://apps.apple.com/fr/app/youtube/id544007664', website:'https://www.youtube.com' },
  { name:'Spotify', grade:'D', category:'Multimédia', icon:'🎵', color:'bg-green-500', developer:'Spotify AB', jurisdiction:'Suède', isEuropean:true, isOpenSource:false, popularity:12, reason:'Siège européen mais collecte données détaillées : humeur, habitudes d\'écoute, localisation. Partage avec artistes et annonceurs pour le ciblage.', description:'Premier service de streaming musical mondial. 600 millions d\'utilisateurs actifs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.spotify.music', appleStoreUrl:'https://apps.apple.com/fr/app/spotify/id324684580', website:'https://www.spotify.com' },
  { name:'Netflix', grade:'C', category:'Multimédia', icon:'🎬', color:'bg-red-700', developer:'Netflix Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:13, reason:'Collecte les habitudes de visionnage et l\'utilise pour la recommandation. Moins intrusif que les réseaux sociaux. Pas de revente à des tiers.', description:'Service de streaming vidéo. 270 millions d\'abonnés dans le monde.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.netflix.mediaclient', appleStoreUrl:'https://apps.apple.com/fr/app/netflix/id363590051', website:'https://www.netflix.com' },
  { name:'Deezer', grade:'B', category:'Multimédia', icon:'🎶', color:'bg-purple-600', developer:'Deezer SA', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:24, reason:'Entreprise française, soumise au RGPD. Politique de confidentialité transparente. Collecte les habitudes d\'écoute mais sans profilage publicitaire agressif.', description:'Service de streaming musical français. 120 millions de titres disponibles.', playStoreUrl:'https://play.google.com/store/apps/details?id=deezer.android.app', appleStoreUrl:'https://apps.apple.com/fr/app/deezer-music-player/id292738169', website:'https://www.deezer.com' },
  { name:'Twitch', grade:'D', category:'Multimédia', icon:'🎮', color:'bg-purple-700', developer:'Amazon', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:30, reason:'Appartient à Amazon. Collecte données détaillées de visionnage, préférences, achats. Intégration avec l\'écosystème Amazon.', description:'Plateforme de streaming de jeux vidéo et de contenu en direct. 140 millions d\'utilisateurs.', playStoreUrl:'https://play.google.com/store/apps/details?id=tv.twitch.android.app', appleStoreUrl:'https://apps.apple.com/fr/app/twitch/id460177396', website:'https://www.twitch.tv' },
  { name:'Disney+', grade:'C', category:'Multimédia', icon:'🏰', color:'bg-blue-800', developer:'The Walt Disney Company', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:31, reason:'Collecte les habitudes de visionnage. Politique de confidentialité standard, pas de revente directe à des tiers pour la publicité.', description:'Service de streaming Disney, Marvel, Star Wars, Pixar, National Geographic.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.disney.disneyplus', appleStoreUrl:'https://apps.apple.com/fr/app/disney/id1446075923', website:'https://www.disneyplus.com' },
  { name:'Molotov', grade:'B', category:'Multimédia', icon:'📺', color:'bg-indigo-700', developer:'Molotov SAS', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:42, reason:'Startup française soumise au RGPD. Collecte les habitudes de visionnage mais dans un cadre légal européen strict.', description:'Application française de TV en direct et en replay. Accès gratuit aux chaînes françaises.', playStoreUrl:'https://play.google.com/store/apps/details?id=tv.molotov.app', appleStoreUrl:'https://apps.apple.com/fr/app/molotov-tv-en-direct-et-replay/id1088691940', website:'https://www.molotov.tv' },
  { name:'France Télévisions', grade:'B', category:'Multimédia', icon:'📡', color:'bg-blue-600', developer:'France Télévisions', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:44, reason:'Service public français. Collecte minimale, pas de revente de données à des fins commerciales. Conforme au RGPD.', description:'Application officielle de France TV : France 2, France 3, France 4, France 5. Replay gratuit.', playStoreUrl:'https://play.google.com/store/apps/details?id=fr.francetv.pluzz', appleStoreUrl:'https://apps.apple.com/fr/app/france-tv/id394847226', website:'https://www.france.tv' },
  { name:'Arte', grade:'A', category:'Multimédia', icon:'🎭', color:'bg-orange-600', developer:'Arte G.E.I.E.', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:48, reason:'Chaîne publique franco-allemande. Politique exemplaire : pas de publicité ciblée, données non revendues, conformité RGPD totale.', description:'La chaîne culturelle franco-allemande. Films, documentaires, séries, concerts en replay.', playStoreUrl:'https://play.google.com/store/apps/details?id=tv.arte.plus7', appleStoreUrl:'https://apps.apple.com/fr/app/arte/id405028510', website:'https://www.arte.tv' },
  { name:'Amazon Prime Video', grade:'C', category:'Multimédia', icon:'🎥', color:'bg-blue-500', developer:'Amazon', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:29, reason:'Appartient à Amazon. Collecte les habitudes de visionnage. Intégration avec le profil Amazon Shopping pour le ciblage publicitaire.', description:'Service de streaming vidéo d\'Amazon. Films, séries originales Amazon.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.amazon.avod.thirdpartyclient', appleStoreUrl:'https://apps.apple.com/fr/app/amazon-prime-video/id545519333', website:'https://www.primevideo.com' },

  // NAVIGATION & TRANSPORT
  { name:'Google Maps', grade:'D', category:'Navigation', icon:'🗺️', color:'bg-green-600', developer:'Google', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:6, reason:'Historique de localisation complet envoyé à Google. Utilisé pour la publicité géolocalisée. Très précis mais très intrusif.', description:'Application de navigation et cartographie de Google. 1 milliard d\'utilisateurs actifs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.google.android.apps.maps', appleStoreUrl:'https://apps.apple.com/fr/app/google-maps/id585027354', website:'https://maps.google.com' },
  { name:'Waze', grade:'D', category:'Navigation', icon:'🚗', color:'bg-cyan-500', developer:'Google (Waze Mobile)', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:19, reason:'Racheté par Google. Collecte en continu la localisation et les trajets. Données utilisées pour améliorer Google Maps et le ciblage publicitaire.', description:'Application de navigation communautaire avec alertes temps réel (radars, embouteillages).', playStoreUrl:'https://play.google.com/store/apps/details?id=com.waze', appleStoreUrl:'https://apps.apple.com/fr/app/waze-navigation-live-traffic/id323229106', website:'https://www.waze.com' },
  { name:'OsmAnd', grade:'A', category:'Navigation', icon:'🧭', color:'bg-green-700', developer:'OsmAnd BV', jurisdiction:'Pays-Bas', isEuropean:true, isOpenSource:true, popularity:72, reason:'Open source basé sur OpenStreetMap. Fonctionne entièrement hors ligne. Aucune donnée de localisation envoyée à des serveurs tiers.', description:'Navigation hors ligne basée sur OpenStreetMap. Aucune collecte de données, open source.', playStoreUrl:'https://play.google.com/store/apps/details?id=net.osmand', appleStoreUrl:'https://apps.apple.com/fr/app/osmand-maps-travel-navigate/id934850257', website:'https://osmand.net', githubUrl:'https://github.com/osmandapp/OsmAnd' },
  { name:'SNCF Connect', grade:'C', category:'Transport & Voyage', icon:'🚄', color:'bg-red-600', developer:'SNCF Connect & Tech', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:32, reason:'Entreprise française publique soumise au RGPD. Collecte les données de trajets et de fidélité. Pas de revente à des tiers publicitaires.', description:'Application officielle SNCF pour acheter des billets de train et gérer ses voyages.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.vsct.vsc.mobile.horaireetresa.sncf', appleStoreUrl:'https://apps.apple.com/fr/app/sncf-connect/id399793692', website:'https://www.sncf-connect.com' },
  { name:'BlaBlaCar', grade:'B', category:'Transport & Voyage', icon:'🚙', color:'bg-blue-500', developer:'BlaBlaCar SAS', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:36, reason:'Licorne française soumise au RGPD. Collecte les données de trajet pour le service. Politique transparente, pas de revente à des tiers publicitaires.', description:'Plateforme française de covoiturage longue distance. Leader européen du secteur.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.comuto', appleStoreUrl:'https://apps.apple.com/fr/app/blablacar-covoiturage-et-bus/id341329033', website:'https://www.blablacar.fr' },
  { name:'Uber', grade:'D', category:'Transport & Voyage', icon:'🚖', color:'bg-slate-900', developer:'Uber Technologies', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:25, reason:'Collecte la localisation en permanence, même en arrière-plan. Historique des trajets partagé avec des partenaires publicitaires. Nombreux scandales de confidentialité.', description:'Application de VTC (voiture avec chauffeur). Disponible dans 70+ pays.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.ubercab', appleStoreUrl:'https://apps.apple.com/fr/app/uber-commandez-une-course/id368677368', website:'https://www.uber.com' },
  { name:'RATP', grade:'C', category:'Transport & Voyage', icon:'🚇', color:'bg-blue-700', developer:'RATP Dev', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:39, reason:'Service public français. Collecte la localisation pour optimiser les itinéraires. Conforme RGPD, données non revendues.', description:'Application officielle des transports en commun parisiens. Plans, horaires, itinéraires.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.fabernovel.ratp', appleStoreUrl:'https://apps.apple.com/fr/app/ratp/id507108406', website:'https://www.ratp.fr' },

  // SHOPPING
  { name:'Vinted', grade:'C', category:'Shopping', icon:'👗', color:'bg-teal-500', developer:'Vinted UAB', jurisdiction:'Lituanie', isEuropean:true, isOpenSource:false, popularity:20, reason:'Startup européenne soumise au RGPD. Collecte les données de navigation et d\'achat. Politique relativement transparente comparée aux géants du e-commerce.', description:'Marketplace de vêtements de seconde main. Leader en France avec 23 millions d\'utilisateurs.', playStoreUrl:'https://play.google.com/store/apps/details?id=fr.vinted', appleStoreUrl:'https://apps.apple.com/fr/app/vinted/id632064380', website:'https://www.vinted.fr' },
  { name:'Leboncoin', grade:'C', category:'Shopping', icon:'📦', color:'bg-orange-500', developer:'Adevinta (Leboncoin)', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:21, reason:'Siège français, conforme RGPD. Collecte les données de navigation et annonces pour améliorer les recommandations. Publicité ciblée modérée.', description:'Plus grande plateforme de petites annonces en France. 30 millions d\'utilisateurs actifs.', playStoreUrl:'https://play.google.com/store/apps/details?id=fr.leboncoin', appleStoreUrl:'https://apps.apple.com/fr/app/leboncoin/id484115113', website:'https://www.leboncoin.fr' },
  { name:'Temu', grade:'E', category:'Shopping', icon:'🛒', color:'bg-orange-600', developer:'PDD Holdings (Pinduoduo)', jurisdiction:'Chine', isEuropean:false, isOpenSource:false, popularity:23, reason:'Entreprise chinoise. Collecte massive de données (contacts, localisation, biométrie, photos). Multiples enquêtes pour pratiques abusives. Très intrusif.', description:'Marketplace de produits à très bas prix. Appartient au géant chinois Pinduoduo.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.einnovation.temu', appleStoreUrl:'https://apps.apple.com/fr/app/temu-achats-en-ligne/id1641486558', website:'https://www.temu.com' },
  { name:'Shein', grade:'E', category:'Shopping', icon:'👚', color:'bg-slate-950', developer:'SHEIN Group', jurisdiction:'Singapour', isEuropean:false, isOpenSource:false, popularity:26, reason:'Collecte extensive de données personnelles. Enquêtes pour violation de données et pratiques opaques. Code de l\'app a été trouvé à accéder aux contacts sans permission.', description:'Fast fashion en ligne. Controversée pour ses pratiques environnementales et de données.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.zzkko', appleStoreUrl:'https://apps.apple.com/fr/app/shein-shopping-mode-femme/id878577184', website:'https://www.shein.com' },
  { name:'Cdiscount', grade:'C', category:'Shopping', icon:'🏪', color:'bg-red-600', developer:'Cdiscount SA', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:43, reason:'Entreprise française soumise au RGPD. Collecte données d\'achat et navigation. Publicité ciblée mais dans le cadre légal européen.', description:'Deuxième marketplace française. Électronique, électroménager, mode, et plus.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.cdiscount.android', appleStoreUrl:'https://apps.apple.com/fr/app/cdiscount-shopping-pas-cher/id380866648', website:'https://www.cdiscount.com' },
  { name:'Too Good To Go', grade:'B', category:'Shopping', icon:'🥡', color:'bg-teal-600', developer:'Too Good To Go ApS', jurisdiction:'Danemark', isEuropean:true, isOpenSource:false, popularity:41, reason:'Startup européenne (Danemark). RGPD respecté. Collecte uniquement les données nécessaires au service. Mission anti-gaspillage.', description:'App anti-gaspillage alimentaire. Achète des paniers surprises chez les restaurants et commerces.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.app.tgtg', appleStoreUrl:'https://apps.apple.com/fr/app/too-good-to-go-antigaspi/id1060683933', website:'https://www.toogoodtogo.fr' },

  // FINANCE
  { name:'PayPal', grade:'C', category:'Finance', icon:'💳', color:'bg-blue-700', developer:'PayPal Holdings', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:27, reason:'Collecte les données financières et de transaction. Partage avec des tiers pour la détection de fraude. Politique de confidentialité acceptable mais américaine.', description:'Service de paiement en ligne mondial. 430 millions de comptes actifs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.paypal.android.p2pmobile', appleStoreUrl:'https://apps.apple.com/fr/app/paypal-envoyez-de-l-argent/id283646709', website:'https://www.paypal.com' },
  { name:'Wero', grade:'B', category:'Finance', icon:'💸', color:'bg-teal-600', developer:'European Payments Initiative', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:33, reason:'Initiative bancaire européenne française. Successeur de Paylib. RGPD respecté, données uniquement utilisées pour le service de paiement.', description:'Solution de paiement mobile européenne. Successeur de Paylib, portée par les banques françaises.', playStoreUrl:'https://play.google.com/store/apps/details?id=eu.epi.wero', appleStoreUrl:'https://apps.apple.com/fr/app/wero/id1663420997', website:'https://www.wero.eu' },
  { name:'Revolut', grade:'C', category:'Finance', icon:'💰', color:'bg-slate-900', developer:'Revolut Ltd', jurisdiction:'Royaume-Uni', isEuropean:true, isOpenSource:false, popularity:34, reason:'Startup fintech britannique. Collecte des données financières détaillées. Politique de confidentialité acceptable, conforme RGPD.', description:'Application bancaire numérique. Compte bancaire, carte, échange de devises et investissements.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.revolut.revolut', appleStoreUrl:'https://apps.apple.com/fr/app/revolut/id932456704', website:'https://www.revolut.com' },
  { name:'Lydia / Sumeria', grade:'B', category:'Finance', icon:'🏦', color:'bg-indigo-600', developer:'Lydia Solutions', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:45, reason:'Startup française agréée par la Banque de France. RGPD respecté. Données utilisées uniquement pour le service bancaire, pas de revente.', description:'Application de paiement mobile française. Paiement entre amis, compte bancaire, carte Visa.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.lydia', appleStoreUrl:'https://apps.apple.com/fr/app/lydia-paiement-entre-amis/id504978135', website:'https://www.sumeria.eu' },
  { name:'Boursobank', grade:'C', category:'Finance', icon:'🏛️', color:'bg-green-700', developer:'Boursorama Banque', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:46, reason:'Banque en ligne française, filiale de Société Générale. Soumise aux réglementations bancaires européennes. Données financières protégées.', description:'Banque en ligne française. Compte courant, épargne, bourse, crédit immobilier.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.boursorama.android.client', appleStoreUrl:'https://apps.apple.com/fr/app/boursobank-anciennement-boursorama/id585137161', website:'https://www.boursobank.com' },

  // SANTÉ & SPORT
  { name:'Doctolib', grade:'B', category:'Santé & Sport', icon:'🩺', color:'bg-blue-500', developer:'Doctolib SAS', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:17, reason:'Licorne française hébergée en Europe (AWS Frankfurt). Données de santé chiffrées, conformité HDS. Engagement fort pour la confidentialité.', description:'Plateforme française de prise de rendez-vous médicaux. 70 millions de patients en Europe.', playStoreUrl:'https://play.google.com/store/apps/details?id=fr.doctolib.android', appleStoreUrl:'https://apps.apple.com/fr/app/doctolib/id1336379601', website:'https://www.doctolib.fr' },
  { name:'Yuka', grade:'B', category:'Santé & Sport', icon:'🥗', color:'bg-emerald-600', developer:'Yuka SAS', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:37, reason:'Startup française indépendante. Modèle premium, pas de revente de données. Politique de confidentialité exemplaire. Certifiée B Corp.', description:'Application française d\'analyse des produits alimentaires et cosmétiques par scan de code-barres.', playStoreUrl:'https://play.google.com/store/apps/details?id=io.yuka.android', appleStoreUrl:'https://apps.apple.com/fr/app/yuka-scan-des-aliments/id1181185871', website:'https://yuka.io' },
  { name:'Strava', grade:'C', category:'Santé & Sport', icon:'🏃', color:'bg-orange-600', developer:'Strava Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:47, reason:'Collecte la localisation GPS en continu lors des activités. Incident notable en 2018 : révélation de bases militaires via les données agrégées.', description:'Application de suivi sportif (course, cyclisme). Réseau social fitness avec 120 millions d\'utilisateurs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.strava', appleStoreUrl:'https://apps.apple.com/fr/app/strava/id426826309', website:'https://www.strava.com' },
  { name:'Ameli', grade:'B', category:'Santé & Sport', icon:'🏥', color:'bg-blue-600', developer:'Assurance Maladie', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:40, reason:'Application du service public français. Données de santé soumises aux réglementations HDS. Aucune revente commerciale. CNIL-compliant.', description:'Application officielle de l\'Assurance Maladie. Attestations, remboursements, cartes Vitale.', playStoreUrl:'https://play.google.com/store/apps/details?id=fr.cnamts.ameli', appleStoreUrl:'https://apps.apple.com/fr/app/ameli/id620709580', website:'https://www.ameli.fr' },
  { name:'Withings Health Mate', grade:'B', category:'Santé & Sport', icon:'❤️', color:'bg-red-500', developer:'Withings SAS', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:58, reason:'Entreprise française pionnière en santé connectée. Données de santé chiffrées et stockées en Europe. Politique transparente, pas de revente.', description:'Application de santé connectée Withings. Suivi du poids, sommeil, tension et activité physique.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.withings.wiscale2', appleStoreUrl:'https://apps.apple.com/fr/app/withings-health-mate/id542701020', website:'https://www.withings.com' },

  // IA
  { name:'ChatGPT', grade:'C', category:'IA', icon:'🤖', color:'bg-emerald-700', developer:'OpenAI', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:1, reason:'Les conversations peuvent être utilisées pour l\'entraînement (désactivable). Données stockées aux USA. Politique améliorée mais préoccupations subsistent.', description:'Assistant IA de référence. 180 millions d\'utilisateurs actifs. GPT-4 en version premium.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.openai.chatgpt', appleStoreUrl:'https://apps.apple.com/fr/app/chatgpt/id6448311069', website:'https://chat.openai.com' },
  { name:'Gemini', grade:'D', category:'IA', icon:'✨', color:'bg-blue-600', developer:'Google', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:10, reason:'Appartient à Google. Les conversations alimentent le profil Google. Données intégrées à l\'écosystème de collecte publicitaire de Google.', description:'Assistant IA de Google. Intégré à l\'écosystème Google (Gmail, Drive, Search).', playStoreUrl:'https://play.google.com/store/apps/details?id=com.google.android.apps.bard', appleStoreUrl:'https://apps.apple.com/fr/app/google-gemini/id6477489729', website:'https://gemini.google.com' },
  { name:'Mistral', grade:'B', category:'IA', icon:'🌬️', color:'bg-orange-600', developer:'Mistral AI', jurisdiction:'France', isEuropean:true, isOpenSource:true, popularity:50, reason:'Startup française, modèles open source. Données traitées en Europe. Politique de confidentialité conforme au RGPD. Champion européen de l\'IA.', description:'Assistant IA de la startup française Mistral AI. Modèles open source de très haute performance.', website:'https://chat.mistral.ai' },
  { name:'Perplexity', grade:'C', category:'IA', icon:'🔍', color:'bg-teal-600', developer:'Perplexity AI Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:53, reason:'Startup américaine. Utilise les requêtes pour améliorer le modèle. Politique acceptable mais américaine. Option pour désactiver le tracking.', description:'Moteur de recherche IA avec sources citées. Concurrent de ChatGPT orienté recherche web.', playStoreUrl:'https://play.google.com/store/apps/details?id=ai.perplexity.app.android', appleStoreUrl:'https://apps.apple.com/fr/app/perplexity-ask-anything/id1668000334', website:'https://www.perplexity.ai' },

  // SÉCURITÉ & VPN
  { name:'Bitwarden', grade:'A', category:'Sécurité & VPN', icon:'🔐', color:'bg-blue-600', developer:'Bitwarden Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:true, popularity:62, reason:'Open source, chiffrement de bout en bout côté client. Audit de sécurité indépendant. Peut être auto-hébergé. La référence des gestionnaires de mots de passe.', description:'Gestionnaire de mots de passe open source. Gratuit, multi-plateforme et très sécurisé.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.x8bit.bitwarden', appleStoreUrl:'https://apps.apple.com/fr/app/bitwarden-password-manager/id1137397744', website:'https://bitwarden.com', githubUrl:'https://github.com/bitwarden' },
  { name:'Dashlane', grade:'B', category:'Sécurité & VPN', icon:'🛡️', color:'bg-green-600', developer:'Dashlane SAS', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:60, reason:'Startup française originaire de Paris. Architecture zéro-connaissance : même Dashlane ne peut pas lire tes mots de passe. RGPD respecté.', description:'Gestionnaire de mots de passe français. Architecture zéro-connaissance et interface soignée.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.dashlane', appleStoreUrl:'https://apps.apple.com/fr/app/dashlane-gestionnaire-mdp/id517914017', website:'https://www.dashlane.com' },
  { name:'ProtonVPN', grade:'A', category:'Sécurité & VPN', icon:'🔒', color:'bg-purple-700', developer:'Proton AG', jurisdiction:'Suisse', isEuropean:true, isOpenSource:true, popularity:65, reason:'Entreprise suisse, open source, politique de non-journalisation auditée. Chiffrement fort, pas de fuites DNS. La meilleure option pour la vie privée.', description:'VPN open source de Proton. Basé en Suisse, politique no-log vérifiée par audit indépendant.', playStoreUrl:'https://play.google.com/store/apps/details?id=ch.protonvpn.android', appleStoreUrl:'https://apps.apple.com/fr/app/proton-vpn-fast-secure/id1437005085', website:'https://protonvpn.com', githubUrl:'https://github.com/ProtonVPN' },
  { name:'NordVPN', grade:'B', category:'Sécurité & VPN', icon:'🛡️', color:'bg-blue-700', developer:'Nord Security', jurisdiction:'Panama', isEuropean:false, isOpenSource:false, popularity:63, reason:'Politique no-log vérifiée par audit indépendant. Incident de sécurité en 2018 corrigé depuis. Très populaire et fiable.', description:'Un des VPN les plus populaires. Serveurs dans 60+ pays, politique no-log auditée.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.nordvpn.android', appleStoreUrl:'https://apps.apple.com/fr/app/nordvpn-vpn-fast-secure/id905953485', website:'https://nordvpn.com' },

  // PRODUCTIVITÉ
  { name:'Notion', grade:'C', category:'Productivité/Organisation', icon:'📝', color:'bg-slate-800', developer:'Notion Labs Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:49, reason:'Données stockées aux USA. Contenu accessible par les employés Notion. Politique acceptable mais quelques inquiétudes sur l\'accès aux données sensibles.', description:'Application de productivité tout-en-un : notes, bases de données, wikis, gestion de projets.', playStoreUrl:'https://play.google.com/store/apps/details?id=notion.id', appleStoreUrl:'https://apps.apple.com/fr/app/notion-notes-projets-tâches/id1232780281', website:'https://www.notion.so' },
  { name:'Microsoft Teams', grade:'C', category:'Productivité/Organisation', icon:'👥', color:'bg-indigo-700', developer:'Microsoft', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:51, reason:'Collecte données professionnelles et comportementales. Conformité RGPD disponible mais nécessite configuration. Données dans les datacenters Microsoft.', description:'Plateforme de collaboration Microsoft. Chat, visio, fichiers. Très utilisée en entreprise.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.microsoft.teams', appleStoreUrl:'https://apps.apple.com/fr/app/microsoft-teams/id1113153706', website:'https://www.microsoft.com/fr-fr/microsoft-teams' },
  { name:'Zoom', grade:'C', category:'Productivité/Organisation', icon:'📹', color:'bg-blue-500', developer:'Zoom Video Communications', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:54, reason:'Données routées via la Chine en 2020 (corrigé depuis). Collecte des données de réunion, enregistrements. Politique améliorée mais surveillance possible.', description:'Application de visioconférence professionnelle. 300 millions de participants journaliers au pic.', playStoreUrl:'https://play.google.com/store/apps/details?id=us.zoom.videomeetings', appleStoreUrl:'https://apps.apple.com/fr/app/zoom-one-platform-to-connect/id546505307', website:'https://zoom.us' },
  { name:'Google Drive', grade:'D', category:'Productivité/Organisation', icon:'☁️', color:'bg-yellow-500', developer:'Google', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:16, reason:'Google analyse le contenu des fichiers pour la personnalisation et la publicité. Aucun chiffrement côté client par défaut. Données accessibles par Google.', description:'Service de stockage en nuage Google. 15 Go gratuits, intégré à Gmail et Google Docs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.google.android.apps.docs', appleStoreUrl:'https://apps.apple.com/fr/app/google-drive-stockage-en-ligne/id507874739', website:'https://drive.google.com' },

  // UTILITAIRES
  { name:'France Identité', grade:'B', category:'Utilitaires', icon:'🪪', color:'bg-blue-800', developer:'Agence Nationale des Titres Sécurisés', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:56, reason:'Application d\'État français. Données biométriques stockées localement, pas transmises. Conforme aux plus hauts standards de sécurité. Audité par l\'ANSSI.', description:'Application officielle de l\'État pour numériser sa carte nationale d\'identité.', playStoreUrl:'https://play.google.com/store/apps/details?id=fr.gouv.agentconnect.france_identite', appleStoreUrl:'https://apps.apple.com/fr/app/france-identit%C3%A9/id1596579491', website:'https://france-identite.gouv.fr' },
  { name:'Météo-France', grade:'B', category:'Utilitaires', icon:'⛅', color:'bg-sky-500', developer:'Météo-France', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:57, reason:'Service public français. Collecte uniquement la localisation pour les prévisions. Aucune revente de données à des tiers commerciaux.', description:'Application officielle de Météo-France. Prévisions précises, alertes météo en temps réel.', playStoreUrl:'https://play.google.com/store/apps/details?id=fr.meteo', appleStoreUrl:'https://apps.apple.com/fr/app/météo-france/id364390290', website:'https://meteofrance.com' },
  { name:'La Poste', grade:'C', category:'Utilitaires', icon:'📬', color:'bg-yellow-500', developer:'La Poste SA', jurisdiction:'France', isEuropean:true, isOpenSource:false, popularity:59, reason:'Entreprise française soumise au RGPD. Collecte les données de livraison et d\'identité. Pas de publicité ciblée.', description:'Application officielle La Poste. Suivi des colis, envoi de courrier, services financiers.', playStoreUrl:'https://play.google.com/store/apps/details?id=fr.laposte.lapostemobile', appleStoreUrl:'https://apps.apple.com/fr/app/la-poste/id526584656', website:'https://www.laposte.fr' },

  // ÉDUCATION & JEUX
  { name:'Duolingo', grade:'C', category:'Éducation', icon:'🦉', color:'bg-green-500', developer:'Duolingo Inc.', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:61, reason:'Collecte les données d\'apprentissage et comportementales. Publicités dans la version gratuite. Politique acceptable mais modèle freemium basé sur les données.', description:'Application d\'apprentissage des langues gamifiée. 74 langues, 500 millions d\'utilisateurs.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.duolingo', appleStoreUrl:'https://apps.apple.com/fr/app/duolingo-apprendre-des-langues/id570060128', website:'https://www.duolingo.com' },
  { name:'Candy Crush Saga', grade:'D', category:'Jeux', icon:'🍬', color:'bg-purple-500', developer:'Activision Blizzard (King)', jurisdiction:'USA', isEuropean:false, isOpenSource:false, popularity:64, reason:'Appartient à Activision/Microsoft. Collecte données comportementales et d\'achat. Publicités ciblées et achats in-app intrusifs.', description:'Jeu de puzzle match-3 le plus populaire au monde. 250 millions de joueurs actifs mensuels.', playStoreUrl:'https://play.google.com/store/apps/details?id=com.king.candycrushsaga', appleStoreUrl:'https://apps.apple.com/fr/app/candy-crush-saga/id553834731', website:'https://www.king.com/game/candycrush' },
];

// ─── Récupérer les apps existantes ────────────────────────────────────────────

async function getExistingNames() {
  const res = await fetch(`${BASE_URL}/api/apps?limit=500`);
  if (!res.ok) throw new Error(`GET /api/apps failed: ${res.status}`);
  const data = await res.json();
  return new Set((data.apps || []).map(a => a.name.toLowerCase()));
}

// ─── Insérer une app ──────────────────────────────────────────────────────────

async function insertApp(app) {
  const res = await fetch(`${BASE_URL}/api/apps`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(app),
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`POST failed (${res.status}): ${txt}`);
  }
  return res.json();
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`\n🚀 Seed via API — ${APPS.length} apps à vérifier\n`);

  const existingNames = await getExistingNames();
  console.log(`📦 Apps déjà en base : ${existingNames.size}\n`);

  let inserted = 0;
  let skipped = 0;

  for (const app of APPS) {
    if (existingNames.has(app.name.toLowerCase())) {
      console.log(`  ⏭  Ignoré  : ${app.name}`);
      skipped++;
      continue;
    }

    try {
      await insertApp(app);
      console.log(`  ✅ Inséré  : ${app.name} (${app.grade})`);
      inserted++;
      // petite pause pour ne pas saturer l'API
      await new Promise(r => setTimeout(r, 100));
    } catch (err) {
      console.error(`  ❌ Erreur  : ${app.name} — ${err.message}`);
    }
  }

  console.log(`\n✨ Terminé ! ${inserted} apps insérées, ${skipped} ignorées.\n`);
}

main().catch(err => { console.error('Fatal:', err); process.exit(1); });
