/**
 * Signatures des produits Google connus. Chaque entrée est indépendante et
 * peut être ajoutée/modifiée sans toucher au moteur de détection
 * (voir database/SignatureDatabase.js et analyzer/*).
 *
 * packagePrefixes : préfixes de noms de classes pleinement qualifiés
 * recherchés parmi les composants déclarés dans le manifeste (services,
 * receivers, providers, activities).
 * metaDataKeys : clés <meta-data> recherchées (app-level ou par composant).
 */
export const GOOGLE_SIGNATURES = [
  {
    id: 'google_play_services',
    name: 'Google Play Services',
    vendor: 'Google',
    category: 'Services système Google',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.google.android.gms.'],
    metaDataKeys: ['com.google.android.gms.version'],
    description: 'Socle de services Google (localisation, sécurité, etc.) utilisé par de nombreuses apps Android.',
  },
  {
    id: 'firebase_core',
    name: 'Firebase',
    vendor: 'Google',
    category: 'Plateforme applicative',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.google.firebase.provider.', 'com.google.firebase.components.'],
    metaDataKeys: ['com.google.firebase.messaging.default_notification_icon'],
    description: 'Plateforme Google regroupant plusieurs services (notifications, base de données, authentification...).',
  },
  {
    id: 'firebase_cloud_messaging',
    name: 'Firebase Cloud Messaging',
    vendor: 'Google',
    category: 'Notifications push',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.google.firebase.messaging.'],
    metaDataKeys: [],
    description: 'Service de notifications push de Google/Firebase.',
  },
  {
    id: 'firebase_analytics',
    name: 'Firebase Analytics',
    vendor: 'Google',
    category: 'Mesure d\'audience',
    isGoogleProduct: true,
    trackerCategory: 'analytics',
    packagePrefixes: ['com.google.firebase.analytics.', 'com.google.android.gms.measurement.'],
    metaDataKeys: [],
    description: 'Mesure d\'audience et d\'usage de l\'application, proposée par Google/Firebase.',
  },
  {
    id: 'firebase_crashlytics',
    name: 'Firebase Crashlytics',
    vendor: 'Google',
    category: 'Rapport de plantage',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.google.firebase.crashlytics.'],
    metaDataKeys: [],
    description: 'Collecte des rapports de plantage (crash) pour le développeur.',
  },
  {
    id: 'google_maps',
    name: 'Google Maps',
    vendor: 'Google',
    category: 'Cartographie',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.google.android.gms.maps.'],
    metaDataKeys: ['com.google.android.geo.API_KEY', 'com.google.android.maps.v2.API_KEY'],
    description: 'Affichage de cartes et services de localisation Google Maps.',
  },
  {
    id: 'google_sign_in',
    name: 'Google Sign-In',
    vendor: 'Google',
    category: 'Authentification',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.google.android.gms.auth.api.signin.'],
    metaDataKeys: [],
    description: 'Connexion via un compte Google.',
  },
  {
    id: 'google_mobile_ads',
    name: 'Google Mobile Ads (AdMob)',
    vendor: 'Google',
    category: 'Publicité',
    isGoogleProduct: true,
    trackerCategory: 'advertising',
    packagePrefixes: ['com.google.android.gms.ads.'],
    metaDataKeys: ['com.google.android.gms.ads.APPLICATION_ID'],
    description: 'Régie publicitaire mobile de Google.',
  },
  {
    id: 'google_ml_kit',
    name: 'Google ML Kit',
    vendor: 'Google',
    category: 'Machine learning',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.google.mlkit.', 'com.google.android.gms.vision.'],
    metaDataKeys: [],
    description: 'Bibliothèques de machine learning sur l\'appareil (reconnaissance de texte, d\'image, etc.).',
  },
  {
    id: 'google_play_integrity',
    name: 'Google Play Integrity',
    vendor: 'Google',
    category: 'Anti-fraude',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.google.android.play.core.integrity.'],
    metaDataKeys: [],
    description: 'Vérification de l\'intégrité de l\'application et de l\'appareil auprès de Google Play.',
  },
  {
    id: 'google_play_billing',
    name: 'Google Play Billing',
    vendor: 'Google',
    category: 'Paiement',
    isGoogleProduct: true,
    trackerCategory: null,
    packagePrefixes: ['com.android.vending.billing.', 'com.android.billingclient.'],
    metaDataKeys: [],
    description: 'Achats et abonnements in-app via Google Play.',
  },
];

export default GOOGLE_SIGNATURES;
